---
title: "2018 Yearly Analysis"
output: 
  rmdformats::readthedown:
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The data for the year 2015 gives us a benchmark to base our analysis on as 2015 was the first year in business for the given company.

## Preparing Data for Analysis: 

```{r}
library("readxl")
library("ggplot2")
library("dygraphs")
setwd("D:/Case Study")
paths2018 <- vector()
paths2018 <- c(paths2018, paste(getwd(),"/Yearly_Data/2018/Quarterly/Divvy_Trips_2018_Q1.xlsx", sep = ""))
paths2018 <- c(paths2018, paste(getwd(),"/Yearly_Data/2018/Quarterly/Divvy_Trips_2018_Q2.xlsx", sep = ""))
paths2018 <- c(paths2018, paste(getwd(),"/Yearly_Data/2018/Quarterly/Divvy_Trips_2018_Q3.xlsx", sep = ""))
paths2018 <- c(paths2018, paste(getwd(),"/Yearly_Data/2018/Quarterly/Divvy_Trips_2018_Q4.xlsx", sep = ""))
AllPaths <- c(paths2018)
Trips <- list()
for(i in AllPaths)
{
  for(Mypath in i)
  { 
    Trips <- rbind(Trips,read_excel(Mypath, col_types = c("guess","guess","guess","guess","guess","guess","guess","guess","guess","guess","guess","numeric")))
  }
}
```

## Summary of Data: 

```{r}
summary(Trips)
```
## Analysis Metrics: 

* Customer-Sub Ratio
* Gender Demographic
* Trip Duration

## Customer-Sub Ratio:

```{r}
UserTypeCol <- Trips$usertype
Subs <- 0
Customers <- 0

for(i in UserTypeCol)
  if(i == "Subscriber")
    Subs <- Subs + 1 else
      Customers <- Customers + 1
pie(c(Subs,Customers),label = c(paste("Subscribers = ", round(Subs*100/(Subs + Customers), 2), "%"), paste("Customers = ", round(Customers*100/(Subs + Customers), 2), "%")))
```

## Gender Demographic: 
```{r}
ggplot(data = Trips) +
  geom_bar(mapping = aes(x = gender, fill = usertype), stat = "count")
```

## Trip Duration: 
```{r}
ggplot(data = Trips, aes(trip_id, tripduration)) +
        geom_smooth()
```
